services:

  app:
      build: .
      container_name: video-catalog-api
      volumes:
          - .:/var/www
      extra_hosts:
        - "host.docker.internal:host-gateway"
      networks:
          - video-catalog-network

  nginx:
    build: .docker/nginx
    container_name: video-catalog-nginx
    ports:
        - "8000:80"
    volumes:
        - .:/var/www
    networks:
        - video-catalog-network
    depends_on:
        - app

networks:
  video-catalog-network:
    driver: bridge